/*
 * Table of Multi-language phrases
 */
res.config.phrases = {
//  "ComingSoon": ["Coming Soon", "準備中"],
//  "Closed.Message": ["Closed", "準備中"],

    "Credential.Clear": ["Clear", "消す"],
    "Credential.Assist":    ["Assist", "応援者"],
    "Credential.Operator":  ["Operator", "扱者"],
    "Credential.Back":  ["Back", "戻る"],
    "Credential.Passcode":  ["Enter", "入力"],
    "Credential.GuideOperator": ["Please enter your operator ID.<br>Or you can start demo by 2 + 'Enter'.", "扱者番号を入力してください。<br>または、1 +「登録」でデモを開始できます。"],
    "Credential.GuidePasscode": ["Please enter passcode.", "暗証番号を入力してください"],
    "Credential.Rejected":  ["The operator ID or passcode does not match.", "扱者番号または暗証番号が一致しません。"],
    "Credential.GuideToOthers": ["The lane is closed.<br>Please go to other lanes.", "ただいま準備中です。<br>他のレジにお回りください。"],

//  "Notices.Deploy.Menu.Exit": ["Send", "配信"],
    "Notices.Deploy.Menu.Exit": ["Send", "終了<br>(配信)"],
    "Notices.Deploy.Menu.Button.FileSave": ["Cancel", "配信せず<br>中止"],
    "Notices.Deploy.Menu.Button.FileUndo": ["Undo", "元に戻す"],
    "Notices.Deploy.Menu.Button.TaskCreate": ["New Task", "新規予定"],
    "Notices.Deploy.Menu.Button.TaskDelete": ["Delete", "削除する"],
    "Notices.Deploy.Menu.Button.TaskObsolete": ["Task Obsolete", "適用終了"],
    "Notices.Deploy.Menu.Button.TaskUpdate": ["Update", "変更する"],
    "Notices.Deploy.Menu.Button.Address": ["Targets", "適用先一覧"],
    "Notices.Deploy.Menu.Button.CollectLogs": ["Collect Logs", "更新"],
    "Notices.Deploy.Menu.Question.Undo": ["The deployment schedule is being reverted.<br>You changes will be lost.<br><br>Are you sure?",
                                            "全ての予定を元に戻します。<br>変更した内容は失われます。<br><br>よろしいですか。"],
//  "Notices.Deploy.Menu.Question.Exit": ["To abort without delivering.<br>Edited data will be deleted<br><br><br>Are you sure?",
//                                          "配信せず中止します。<br>編集データは削除されます。<br><br>よろしいですか。"],
    "Notices.Deploy.Menu.Question.Exit": ['To exit without delivery.<br><br>Edited data will be saved.<br>To deliver later, please press the "Resen" of home.<br><br>Are you sure you want or to abort.', "配信せずに終了します。<br><br>編集データは保存されます。<br>後で配信するには、ホームの「再配信」を押してください。<br><br>中止してよろしいですか。"],
    "Notices.Deploy.Menu.Question.Remove": ["The task is being deleted.<br><br><br>Are you sure?",
                                            "選択された予定を削除します。<br><br>よろしいですか。"],

    "Notices.Deploy.Menu.Question.RemoveToObsolete": ["Remove the task to obsolete.<br><br><br>Are you sure?", "選択された予定を適用終了します。<br><br>よろしいですか。"],
    "Notices.Deploy.Menu.Feedback.Save.Successful": ["The schedule was successfully saved.","構成適用予定が、保存されましたが。<br>配信されていません。"],
    "Notices.Deploy.Menu.Feedback.Save.Failed": ["Failed to save the schedule.<br>Please check the server connection","構成適用予定を保存できませんでした。<br>接続を確認してください。"],
    "Notices.Deploy.Menu.Feedback.InvokeTransfer.Successful": ["The schedule start transfer successfully.","構成の配信が開始されました。"],
    "Notices.Deploy.Menu.Feedback.InvokeTransfer.Failed": ["Failed to start transfer the schedule.<br>Please check the server connection","構成の配信が開始できませんでした。<br>接続を確認してください。"],
    "Notices.Deploy.Menu.Okay": ["OK","確認"],
    "Notices.Deploy.Menu.No": ["No","いいえ"],
    "Notices.Deploy.Menu.Yes": ["Yes","はい"],
    "Notices.Deploy.Directory.Title": ["Configurations","構成一覧"],
    "Notices.Deploy.Directory.pickList": ["Unnumbered Items","バーコードのない商品"],
    "Notices.Deploy.Directory.notices": ["Operational Notice","業務連絡"],
    "Notices.Deploy.Directory.options": ["Advanced Options","詳細設定"],
    "Notices.Deploy.Directory.usability": ["Usability Settings","操作画面構成"],
    "Notices.Deploy.Directory.effective": ["Deployed","適用中"],
    "Notices.Deploy.Directory.scheduled": ["To Deploy","適用待ち"],
    "Notices.Deploy.Directory.obsolete": ["Obsolete","適用終了"],
    "Notices.Deploy.Directory.draft": ["Draft","下書き"],
    "Notices.Deploy.Tasks.To": ["To: ","対象： "],
    "Notices.Deploy.Tasks.Total": ["Total:","対象数:"],
    "Notices.Deploy.Tasks.Remaining": ["Left:","未開封:"],
    "Notices.Deploy.Tasks.Expire": ["Expire on:","有効期限:"],
    "Notices.Deploy.Tasks.Expire.Obsolete": ["Expire Obsolete:","適用終了"],
//  "Notices.Deploy.Tasks.ToApply": ["To Apply:","未適用:"],
//  "Notices.Deploy.Tasks.ToOpen": ["To Open:","未開封:"],
    "Notices.Deploy.Okay": ["OK", "確定"],
    "Notices.Deploy.Void": ["Void", "取消"],
    "Notices.Deploy.Yes": ["Yes", "はい"],
    "Notices.Deploy.No": ["No", "いいえ"],
    "Notices.Deploy.deleteOrVoid": ["Remove the store", "店舗を削除しますか"],
    "Notices.Deploy.confirmMessage": ["Would you like to delivery", "配信しますか"],
    "Notices.Deploy.Cancel": ["Cancel", "中止"],
    "Notices.Deploy.EditTask.Guide": ["Please select an item to deploy.","適用する構成を選択して下さい。"],
//  "Notices.Deploy.EditTask.ToDeploy": ["To Deploy:","配信する"],
    "Notices.Deploy.EditTask.Draft": ["Draft:","下書き"],
    "Notices.Deploy.EditTask.Target": ["Deploy To","適用店舗"],
    "Notices.Deploy.EditTask.Date": ["Deploy on","適用日付"],
    "Notices.Deploy.EditTask.Time": ["Deploy at","適用時刻"],
    "Notices.Deploy.EditTask.YYYYMMDD": ["YYYYMMDD","YYYYMMDD"],
    "Notices.Deploy.EditTask.HHMM": ["HHMM","HHMM"],
    "Notices.Deploy.EditTask.DeployTimeHour": ["Hour","時"],
    "Notices.Deploy.EditTask.DeployTimeMinute": ["Minute","分"],
    "Notices.Deploy.EditTask.DeployTimeUp": ["▲","▲"],
    "Notices.Deploy.EditTask.DeployTimeDown": ["▼","▼"],
//  "Notices.Deploy.DetailView.ViewTital": ["Left Stores","未開封の店舗"],
    "Notices.Deploy.DetailView.ViewTital": ["Left store detail ","未開封店舗一覧"],
    "Notices.Deploy.DetailView.ViewSave": ["Save to csv file","ＣＳＶへ出力"],
    "Notices.Deploy.DetailView.StoreID": ["Store ID","店舗番号"],
    "Notices.Deploy.DetailView.StoreName": ["Japanese Name","店舗名"],
//  "Notices.Deploy.DetailView.StoreName": ["Japanese Name","日本語名"],
    "Notices.Deploy.DetailView.StoreTel": ["Telphone number","電話番号"],

    "Notices.Deploy.EditStore": ["Edit Store","店舗編集"],
    "Notices.Deploy.EditStore.Guide": ["Please Edit Store or Store Group","適用先を編集します"],
    "Notices.Deploy.EditStore.SearchStore": ["Store numbers/Japanese name","店舗番号/店舗名 で検索"],
    "Notices.Deploy.AddStore": ["Add Store","新規店舗"],
    "Notices.Deploy.AddStoreGroup": ["Add Store Group","新規店舗グループ"],
    "Notices.Deploy.EditStoreGroup": ["Edit Store Group","店舗グループ編集"],

    "Notices.Deploy.AddStore.Guide":["Please Edit Store","店舗を編集します"],
    "Notices.Deploy.DeleteStore":["Delete","削除"],
    "Notices.Deploy.AddStore.storeId":["StoreId","店舗番号"],
    "Notices.Deploy.AddStore.storeEnName":["En Name","英語名"],
    "Notices.Deploy.AddStore.storeJaName":["Ja Name","店舗名"],
//  "Notices.Deploy.AddStore.storeJaName":["Ja Name","日本語名"],
//  "Notices.Deploy.AddStore.storeIP":["IP address","正サーバIP"],
    "Notices.Deploy.AddStore.storeIP":["IP address","プライマリ店舗サーバーIP"],
    "Notices.Deploy.AddStore.storeIPDetail":["IP address","プライマリーIP"],
    "Notices.Deploy.AddStore.storeSecondaryIP":["IP address","セカンダリ店舗サーバーIP"],
    "Notices.Deploy.AddStore.storeSecondaryIPDetail":["IP address","セカンダリIP"],
//  "Notices.Deploy.AddStore.storeSecondaryIP":["IP address","副サーバIP"],
    "Notices.Deploy.AddStore.storeTel":["Telephone number","電話番号"],
    "Notices.Deploy.AddStore.success":["add store success","店舗追加しました"],
    "Notices.Deploy.AddStore.exist":["the store exits","店舗既にあります"],
    "Notices.Deploy.AddStore.failed":["failed to add the store","店舗追加失敗"],
    "Notices.Deploy.AddStore.emptyId":["failed to add the store!storeID can not be empty","店舗番号を空にできません"],
    "Notices.Deploy.AddStore.ExistStoreId":["failed to add the store!the　storeID is already exist","この店舗番号はすでに存在しております"],
    "Notices.Deploy.AddStore.isNotNum":["failed to add the store!storeID must be digits","店舗番号は数字のみ"],
    "Notices.Deploy.AddStore.emptyNmEn":["failed to add the store!English name can not be empty","英語名は空にできません"],
    "Notices.Deploy.AddStore.emptyNmJp":["failed to add the store!Japanese name can not be empty","店舗名は空にできません"],
    "Notices.Deploy.AddStore.emptyIP":["failed to add the store!primary　IP address can not be empty","プライマリ店舗サーバーIPアドレスは空にできません"],
    "Notices.Deploy.AddStore.errorIP":["failed to add the store!primary　IP address format is incorrect","プライマリ店舗サーバーIPアドレスの形式が正しくありません"],
    "Notices.Deploy.AddStore.emptySecondaryIP":["failed to add the store!Secondary　IP address can not be empty","セカンダリ店舗サーバーIPアドレスは空にできません"],
    "Notices.Deploy.AddStore.errorSecondaryIP":["failed to add the store!Secondary　IP address format is incorrect","セカンダリ店舗サーバーIPアドレスの形式が正しくありません"],
    "Notices.Deploy.AddStore.emptyTel":["failed to add the store!Telephone number can not be empty","電話番号は空にできません"],
    "Notices.Deploy.AddStore.errorTel":["failed to add the store!Telephone number format is incorrect","電話番号の形式が正しくありません"],

    "Notices.Deploy.UpdateStore.success":["update store success","店舗変更しました"],
    "Notices.Deploy.UpdateStore.failed":["failed to update the store","店舗変更失敗"],

    "Notices.Deploy.DeleteStore.success":["delete store success","店舗削除しました"],
    "Notices.Deploy.DeleteStore.failed":["failed to delete the store","店舗削除失敗"],

    "Notices.Deploy.AddStoreGroup.Guide":["Please Edit Store Group","店舗グループ編集"],
    "Notices.Deploy.AddStoreGroup.storeGroupName":["Store Group Name","店舗グループ名"],
    "Notices.Deploy.AddStoreGroup.doAdd":["Add","追加"],
    "Notices.Deploy.AddStoreGroup.doDelete":["Delete","削除"],
//  "Notices.Deploy.AddStoreGroup.toRight":["→","→"],
//  "Notices.Deploy.AddStoreGroup.toLeft":["←","←"],

    "Notices.Deploy.AddStoreGroup.success":["add store success","店舗グループ追加しました"],
    "Notices.Deploy.AddStoreGroup.exist":["the store exits","店舗グループ既にあります"],
    "Notices.Deploy.AddStoreGroup.failed":["failed to add the store","店舗グループ追加失敗"],

//  "Notices.Deploy.AddStoreGroup.storeGroupNameEn":["StoreGroup En Name","店舗グループ英語名"],
//  "Notices.Deploy.AddStoreGroup.storeGroupNameJa":["StoreGroup Ja Name","店舗グループ日本名"],
    "Notices.Deploy.AddStoreGroup.storeGroupNameJa":["StoreGroup Ja Name","店舗グループ名"],
    "Notices.Deploy.AddStoreGroup.emptyGroupNameJa":["failed to add the store group! Japanese name can not be empty.","店舗グループ名は空にできません"],

    "Notices.Deploy.AddStoreGroup.storeEntryLTOR":["Store entry list view","店舗一覧"],
    "Notices.Deploy.AddStoreGroup.storeEntryRTOL":["Store group list view","店舗グループ"],

    "Notices.Deploy.UpdateStoreGroup.success":["update store success","店舗変更しました"],
    "Notices.Deploy.UpdateStoreGroup.failed":["failed to update the store","店舗変更失敗"],

    "Notices.Deploy.DeleteStoreGroup.success":["delete store success","店舗グループ削除しました"],
    "Notices.Deploy.DeleteStoreGroup.failed":["failed to delete the store","店舗グループ削除失敗"],

    "Notices.Deploy.Warning.missingTarget":["Targeted stores are not selected.","「適用店舗」が選択されていません。"],
    "Notices.Deploy.Warning.invalidDateTime":["Date/Time is invalid.","無効な日付または時刻です。"],
    "Notices.Deploy.Warning.passedDateTime":["The date/time already passed.","入力された日時は、既に過ぎています。"],
    "Notices.Deploy.Warning.missingFile":["config file is not selected.","配信する構成が選択されていません。"],

    "Notices.Deploy.FileExplorer.Title.Exmport": ["Exmport to new file", "出力先を選択"],
    "Notices.Deploy.FileExplorer.Button.CsvSave":["Save", "保存"],
    "Notices.Deploy.FileExplorer.Button.Back" :["Back","戻る"],
    "Notices.Deploy.FileExplorer.Button.Cancel" :["Cancel","中止"],
    "Notices.Deploy.FileExplorer.Button.Open" :["Open","開く"],
    "Notices.Deploy.FileExplorer.FileName.Name" :["File Name","ファイル名"],
    "Notices.Deploy.FileExplorer.FileName.Length" :["Up to 50 characters", "最大全角25文字"],

    "Notices.Deploy.SaveDetail.FileEntry" :["File Path:", "ファイルパス："],
    "Notices.Deploy.SaveDetail.Button.Back":["Back", "戻る"],
    "Notices.Deploy.SaveDetail.Button.CsvSave":["Save", "保存"],
    "Notices.Deploy.SaveDetail.Button.Cancel" :["Cancel","中止"],
    "Notices.Deploy.SaveDetail.Button.Confirm" :["Confirm","確定"],

    "Notices.Deploy.SaveDetail.Success.Notice" :["File saving is completed!", "ファイルを保存しました！"],
    "Notices.Deploy.SaveDetail.Exist.Overwrite": ["Overwrite existing file", "同名の既存ファイルがあれば上書きする"],
    "Notices.Deploy.SaveDetail.Exist.Notice": ["File with the same name already exists!<br>Please change the file name, or turn on the overwrite option above.",
                                                "同じ名前のファイルがすでに存在します！<br>名前を変更するか、上の上書きオプションをオンにしてください。"],
    "Notices.Deploy.SaveDetail.Warning.IsEmptyName": ["Please fill in the file name.", "ファイル名を入力してください。"],
    "Notices.Deploy.SaveDetail.Warning.InValidName": ["Please fill in the file name a valid file name.", "ファイル名を正しく入力してください。"],
    "Notices.Deploy.SaveDetail.Warning.IsLengthOver": ["Please fill in the file name 50 characters.", "ファイル名を全角25文字以下に入力してください。"],
    "Notices.Deploy.SaveDetail.Error.Notice" :["Access denied. <br>You do not have permission to save in this location. <br>Please get the permission to contact the administrator.",
                                                "アクセスが拒否されました。<br><br>この場所に保存するアクセス許可がありません。<br>管理者に連絡してアクセス許可を取得してください。"],


    "Notices.Album.Menu.Exit":["Exit", "終了"],
    "Notices.Album.Menu.ImageList" :["Image List","画像一覧"],
    "Notices.Album.Menu.ImageImport" :["Import","画像<br>取り込み"],
    "Notices.Album.Menu.ImageDelete" :["Delete Image","画像<br>削除"],
    "Notices.Album.Button.ImageCopyStart":["Import", "取り込む"],
    "Notices.Album.Button.Back" :["Back","戻る"],
    "Notices.Album.Button.Cancel" :["Cancel","中止"],
    "Notices.Album.Button.Delete" :["Delete","削除"],
    "Notices.Album.Button.DeleteAgain" :["Delete Again","再削除"],
    "Notices.Album.Button.Confirm" :["Confirm","確定"],
    "Notices.Album.Button.Open" :["Open","開く"],
    "Notices.Album.Button.Yes": ["Yes", "はい"],
    "Notices.Album.Button.No": ["No", "いいえ"],
    "Notices.Album.EditImage.Recursive" :["CopySubFolder","子フォルダ含め"],
    "Notices.Album.lblFolderFrom" :["Copy File From:","処理対象フォルダ:"],
    "Notices.Album.lblFolderTo" :["Copy File To:","コピー先:"],
    "Notices.Album.ImportSuccess": ["Image import successful.", "画像取り込みに成功しました。"],
    "Notices.Album.ImportFailed": ["Image import failed.", "画像取り込みに失敗しました。"],
    "Notices.Album.ImageList.Guide.Images": ["Image List", "画像一覧"],
    "Notices.Album.ImageList.ComingSoon": ["Coming Soon", "準備中"],
//  "Notices.Album.ImageRemove.Guide": ["Selected file will be removed.<br> Are you sure.", "ファイルを削除します。<br>よろしいですか。"],
    "Notices.Album.ImageRemove.Guide.Confirm": ["The currently selected image has been applied to the product image.<br><br>Are you sure to delete the image?", "選択中の画像は商品画像に適用されています。<br><br>画像を削除しますか。"],
    "Notices.Album.ImageRemove.Guide.Success": ["Delete image successful.", "画像を削除に成功しました。"],
    "Notices.Album.ImageRemove.Guide.Failed": ["Delete image failed.", "画像を削除に失敗しました。"],
    "Notices.Album.Import.Title": ["Import new image file", "新しい画像の取り込み"],
    "Notices.Album.Import.Guide": ["Import new image file", "子フォルダを開くには、ダブルクリック"],



//  "PickList.Deploy.Menu.Exit": ["Send", "配信"],
    "PickList.Deploy.Menu.Exit": ["Send", "終了"],
    /*"PickList.Deploy.Menu.Button.FileSave": ["Cancel", "配信せず<br>中止"],*/
    "PickList.Deploy.Menu.Button.FileSave": ["Cancel", "終了"],
    "PickList.Deploy.Menu.Button.FileUndo": ["Undo", "元に戻す"],
    "PickList.Deploy.Menu.Button.TaskCreate": ["New Task", "新規予定"],
    "PickList.Deploy.Menu.Button.TaskDelete": ["Delete", "削除する"],
    "PickList.Deploy.Menu.Button.TaskUpdate": ["Update", "変更する"],
    "PickList.Deploy.Menu.Button.Address": ["Targets", "適用先一覧"],
    "PickList.Deploy.Menu.Button.CollectLogs": ["Collect Logs", "更新"],
    "PickList.Deploy.Menu.Question.Undo": ["The deployment schedule is being reverted.<br>You changes will be lost.<br><br>Are you sure?",
                                            "全ての予定を元に戻します。<br>変更した内容は失われます。<br><br>よろしいですか。"],
//  "PickList.Deploy.Menu.Question.Exit": ["To abort without delivering.<br>Edited data will be deleted<br><br><br>Are you sure?",
//                                          "配信せず中止します。<br>編集データは削除されます。<br><br>よろしいですか。"],
    "PickList.Deploy.Menu.Question.Exit": ['To exit without delivery.<br><br>Edited data will be saved.<br>To deliver later, please press the "Resen" of home.<br><br>Are you sure you want or to abort.', "配信せずに終了します。<br><br>編集データは保存されます。<br>後で配信するには、ホームの「再配信」を押してください。<br><br>中止してよろしいですか。"],
    "PickList.Deploy.Menu.Question.Remove": ["The task is being deleted.<br><br><br>Are you sure?",
                                                "選択された予定を削除します。<br><br>よろしいですか。"],
    "PickList.Deploy.Menu.Feedback.Save.Successful": ["The schedule was successfully saved.","構成適用予定が、保存されましたが。<br>配信されていません。"],
    "PickList.Deploy.Menu.Feedback.Save.Failed": ["Failed to save the schedule.<br>Please check the server connection","構成適用予定を保存できませんでした。<br>接続を確認してください。"],
    "PickList.Deploy.Menu.Feedback.InvokeTransfer.Successful": ["The schedule start transfer successfully.","構成の配信が開始されました。"],
    "PickList.Deploy.Menu.Feedback.InvokeTransfer.Failed": ["Failed to start transfer the schedule.<br>Please check the server connection","構成の配信が開始できませんでした。<br>接続を確認してください。"],
    "PickList.Deploy.Menu.Okay": ["OK","確認"],
    "PickList.Deploy.Menu.No": ["No","いいえ"],
    "PickList.Deploy.Menu.Yes": ["Yes","はい"],
    "PickList.Deploy.Directory.Title": ["Configurations","構成一覧"],
    "PickList.Deploy.Directory.pickList": ["Unnumbered Items","バーコードのない商品"],
    "PickList.Deploy.Directory.notices": ["Operational Notice","業務連絡"],
    "PickList.Deploy.Directory.options": ["Advanced Options","詳細設定"],
    "PickList.Deploy.Directory.usability": ["Usability Settings","操作画面構成"],
    "PickList.Deploy.Directory.effective": ["Deployed","適用中"],
    "PickList.Deploy.Directory.scheduled": ["To Deploy","適用待ち"],
    "PickList.Deploy.Directory.obsolete": ["Obsolete","適用終了"],
    "PickList.Deploy.Directory.draft": ["Draft","下書き"],
    "PickList.Deploy.Tasks.To": ["To: ","対象： "],
    "PickList.Deploy.Tasks.Total": ["Total:","対象数:"],
    "PickList.Deploy.Tasks.Remaining": ["Left:","未開封:"],
    "PickList.Deploy.Tasks.Expire": ["Expire on:","有効期限:"],
    "PickList.Deploy.Okay": ["OK", "確定"],
    "PickList.Deploy.Void": ["Void", "取消"],
    "PickList.Deploy.Yes": ["Yes", "はい"],
    "PickList.Deploy.No": ["No", "いいえ"],
    "PickList.Deploy.deleteOrVoid": ["Remove the store", "店舗を削除しますか"],
    "PickList.Deploy.confirmMessage": ["Would you like to delivery", "配信しますか"],
    "PickList.Deploy.Cancel": ["Cancel", "中止"],
    "PickList.Deploy.EditTask.Guide": ["Please select an item to deploy.","適用する構成を選択して下さい。"],
    "PickList.Deploy.EditTask.Draft": ["Draft:","下書き"],
    "PickList.Deploy.EditTask.Target": ["Deploy To","適用店舗"],
    "PickList.Deploy.EditTask.Date": ["Deploy on","適用日付"],
    "PickList.Deploy.EditTask.Time": ["Deploy at","適用時刻"],
    "PickList.Deploy.EditTask.YYYYMMDD": ["YYYYMMDD","YYYYMMDD"],
    "PickList.Deploy.EditTask.HHMM": ["HHMM","HHMM"],
    "PickList.Deploy.EditTask.DeployTimeHour": ["Hour","時"],
    "PickList.Deploy.EditTask.DeployTimeMinute": ["Minute","分"],
    "PickList.Deploy.EditTask.DeployTimeUp": ["▲","▲"],
    "PickList.Deploy.EditTask.DeployTimeDown": ["▼","▼"],
    "PickList.Deploy.DetailView.ViewTital": ["Left store detail ","未開封店舗一覧"],
    "PickList.Deploy.DetailView.ViewSave": ["Save to csv file","ＣＳＶへ出力"],
    "PickList.Deploy.DetailView.StoreID": ["Store ID","店舗番号"],
    "PickList.Deploy.DetailView.StoreName": ["Japanese Name","店舗名"],
    "PickList.Deploy.DetailView.StoreTel": ["Telphone number","電話番号"],

    "PickList.Deploy.EditStore": ["Edit Store","店舗編集"],
    "PickList.Deploy.EditStore.Guide": ["Please Edit Store or Store Group","適用先を編集します"],
    "PickList.Deploy.EditStore.SearchStore": ["Store numbers/Japanese name","店舗番号/店舗名 で検索"],
    "PickList.Deploy.AddStore": ["Add Store","新規店舗"],
    "PickList.Deploy.AddStoreGroup": ["Add Store Group","新規店舗グループ"],
    "PickList.Deploy.EditStoreGroup": ["Edit Store Group","店舗グループ編集"],

    "PickList.Deploy.AddStore.Guide":["Please Edit Store","店舗を編集します"],
    "PickList.Deploy.DeleteStore":["Delete","削除"],
    "PickList.Deploy.AddStore.storeId":["StoreId","店舗番号"],
    "PickList.Deploy.AddStore.storeEnName":["En Name","英語名"],
    "PickList.Deploy.AddStore.storeJaName":["Ja Name","店舗名"],
    "PickList.Deploy.AddStore.storeIP":["IP address","プライマリ店舗サーバーIP"],
    "PickList.Deploy.AddStore.storeIPDetail":["IP address","プライマリーIP"],
    "PickList.Deploy.AddStore.storeSecondaryIP":["IP address","セカンダリ店舗サーバーIP"],
    "PickList.Deploy.AddStore.storeSecondaryIPDetail":["IP address","セカンダリIP"],
    "PickList.Deploy.AddStore.storeTel":["Telephone number","電話番号"],
    "PickList.Deploy.AddStore.success":["add store success","店舗追加しました"],
    "PickList.Deploy.AddStore.exist":["the store exits","店舗既にあります"],
    "PickList.Deploy.AddStore.failed":["failed to add the store","店舗追加失敗"],
    "PickList.Deploy.AddStore.emptyId":["failed to add the store!storeID can not be empty","店舗番号を空にできません"],
    "PickList.Deploy.AddStore.ExistStoreId":["failed to add the store!the　storeID is already exist","この店舗番号はすでに存在しております"],
    "PickList.Deploy.AddStore.isNotNum":["failed to add the store!storeID must be digits","店舗番号は数字のみ"],
    "PickList.Deploy.AddStore.emptyNmEn":["failed to add the store!English name can not be empty","英語名は空にできません"],
    "PickList.Deploy.AddStore.emptyNmJp":["failed to add the store!Japanese name can not be empty","店舗名は空にできません"],
    "PickList.Deploy.AddStore.emptyIP":["failed to add the store!primary　IP address can not be empty","プライマリ店舗サーバーIPアドレスは空にできません"],
    "PickList.Deploy.AddStore.errorIP":["failed to add the store!primary　IP address format is incorrect","プライマリ店舗サーバーIPアドレスの形式が正しくありません"],
    "PickList.Deploy.AddStore.emptySecondaryIP":["failed to add the store!Secondary　IP address can not be empty","セカンダリ店舗サーバーIPアドレスは空にできません"],
    "PickList.Deploy.AddStore.errorSecondaryIP":["failed to add the store!Secondary　IP address format is incorrect","セカンダリ店舗サーバーIPアドレスの形式が正しくありません"],
    "PickList.Deploy.AddStore.emptyTel":["failed to add the store!Telephone number can not be empty","電話番号は空にできません"],
    "PickList.Deploy.AddStore.errorTel":["failed to add the store!Telephone number format is incorrect","電話番号の形式が正しくありません"],

    "PickList.Deploy.UpdateStore.success":["update store success","店舗変更しました"],
    "PickList.Deploy.UpdateStore.failed":["failed to update the store","店舗変更失敗"],

    "PickList.Deploy.DeleteStore.success":["delete store success","店舗削除しました"],
    "PickList.Deploy.DeleteStore.failed":["failed to delete the store","店舗削除失敗"],

    "PickList.Deploy.AddStoreGroup.Guide":["Please Edit Store Group","店舗グループ編集"],
    "PickList.Deploy.AddStoreGroup.storeGroupName":["Store Group Name","店舗グループ名"],
    "PickList.Deploy.AddStoreGroup.doAdd":["Add","追加"],
    "PickList.Deploy.AddStoreGroup.doDelete":["Delete","削除"],

    "PickList.Deploy.AddStoreGroup.success":["add store success","店舗グループ追加しました"],
    "PickList.Deploy.AddStoreGroup.exist":["the store exits","店舗グループ既にあります"],
    "PickList.Deploy.AddStoreGroup.failed":["failed to add the store","店舗グループ追加失敗"],

    "PickList.Deploy.AddStoreGroup.storeGroupNameJa":["StoreGroup Ja Name","店舗グループ名"],
    "PickList.Deploy.AddStoreGroup.emptyGroupNameJa":["failed to add the store group! Japanese name can not be empty.","店舗グループ名は空にできません"],

    "PickList.Deploy.AddStoreGroup.storeEntryLTOR":["Store entry list view","店舗一覧"],
    "PickList.Deploy.AddStoreGroup.storeEntryRTOL":["Store group list view","店舗グループ"],

    "PickList.Deploy.UpdateStoreGroup.success":["update store success","店舗変更しました"],
    "PickList.Deploy.UpdateStoreGroup.failed":["failed to update the store","店舗変更失敗"],

    "PickList.Deploy.DeleteStoreGroup.success":["delete store success","店舗グループ削除しました"],
    "PickList.Deploy.DeleteStoreGroup.failed":["failed to delete the store","店舗グループ削除失敗"],

    "PickList.Deploy.Warning.missingTarget":["Targeted stores are not selected.","「適用店舗」が選択されていません。"],
    "PickList.Deploy.Warning.invalidDateTime":["Date/Time is invalid.","無効な日付または時刻です。"],
    "PickList.Deploy.Warning.passedDateTime":["The date/time already passed.","入力された日時は、既に過ぎています。"],
    "PickList.Deploy.Warning.missingFile":["config file is not selected.","配信する構成が選択されていません。"],

    "PickList.Deploy.FileExplorer.Title.Exmport": ["Exmport to new file", "出力先を選択"],
    "PickList.Deploy.FileExplorer.Button.CsvSave":["Save", "保存"],
    "PickList.Deploy.FileExplorer.Button.Back" :["Back","戻る"],
    "PickList.Deploy.FileExplorer.Button.Cancel" :["Cancel","中止"],
    "PickList.Deploy.FileExplorer.Button.Open" :["Open","開く"],
    "PickList.Deploy.FileExplorer.FileName.Name" :["File Name","ファイル名"],
    "PickList.Deploy.FileExplorer.FileName.Length" :["Up to 50 characters", "最大全角25文字"],

    "PickList.Deploy.SaveDetail.FileEntry" :["File Path:", "ファイルパス："],
    "PickList.Deploy.SaveDetail.Button.Back":["Back", "戻る"],
    "PickList.Deploy.SaveDetail.Button.CsvSave":["Save", "保存"],
    "PickList.Deploy.SaveDetail.Button.Cancel" :["Cancel","中止"],
    "PickList.Deploy.SaveDetail.Button.Confirm" :["Confirm","確定"],

    "PickList.Deploy.SaveDetail.Success.Notice" :["File saving is completed!", "ファイルを保存しました！"],
    "PickList.Deploy.SaveDetail.Exist.Overwrite": ["Overwrite existing file", "同名の既存ファイルがあれば上書きする"],
    "PickList.Deploy.SaveDetail.Exist.Notice": ["File with the same name already exists!<br>Please change the file name, or turn on the overwrite option above.",
                                                "同じ名前のファイルがすでに存在します！<br>名前を変更するか、上の上書きオプションをオンにしてください。"],
    "PickList.Deploy.SaveDetail.Warning.IsEmptyName": ["Please fill in the file name.", "ファイル名を入力してください。"],
    "PickList.Deploy.SaveDetail.Warning.InValidName": ["Please fill in the file name a valid file name.", "ファイル名を正しく入力してください。"],
    "PickList.Deploy.SaveDetail.Warning.IsLengthOver": ["Please fill in the file name 50 characters.", "ファイル名を全角25文字以下に入力してください。"],
    "PickList.Deploy.SaveDetail.Error.Notice" :["Access denied. <br>You do not have permission to save in this location. <br>Please get the permission to contact the administrator.",
                                                "アクセスが拒否されました。<br><br>この場所に保存するアクセス許可がありません。<br>管理者に連絡してアクセス許可を取得してください。"],



    "PickList.Album.Menu.Exit":["Exit", "終了"],
    "PickList.Album.Menu.ImageList" :["Image List","画像一覧"],
    "PickList.Album.Menu.ImageImport" :["Import","画像<br>取り込み"],
    "PickList.Album.Menu.ImageDelete" :["Delete Image","画像<br>削除"],
    "PickList.Album.Button.ImageCopyStart":["Import", "取り込む"],
    "PickList.Album.Button.Back" :["Back","戻る"],
    "PickList.Album.Button.Cancel" :["Cancel","中止"],
    "PickList.Album.Button.Delete" :["Delete","削除"],
    "PickList.Album.Button.DeleteAgain" :["Delete Again","再削除"],
    "PickList.Album.Button.Confirm" :["Confirm","確定"],
    "PickList.Album.Button.Open" :["Open","開く"],
    "PickList.Album.Button.Yes": ["Yes", "はい"],
    "PickList.Album.Button.No": ["No", "いいえ"],
    "PickList.Album.EditImage.Recursive" :["CopySubFolder","子フォルダ含め"],
    "PickList.Album.lblFolderFrom" :["Copy File From:","処理対象フォルダ:"],
    "PickList.Album.lblFolderTo" :["Copy File To:","コピー先:"],
    "PickList.Album.ImportSuccess": ["Image import successful.", "画像取り込みに成功しました。"],
    "PickList.Album.ImportFailed": ["Image import failed.", "画像取り込みに失敗しました。"],
    "PickList.Album.ImageList.Guide.Images": ["Image List", "画像一覧"],
    "PickList.Album.ImageList.ComingSoon": ["Coming Soon", "準備中"],
//  "PickList.Album.ImageRemove.Guide": ["Selected file will be removed.<br> Are you sure.", "ファイルを削除します。<br>よろしいですか。"],
    "PickList.Album.ImageRemove.Guide.Confirm": ["The currently selected image has been applied to the product image.<br><br>Are you sure to delete the image?", "選択中の画像は商品画像に適用されています。<br><br>画像を削除しますか。"],
    "PickList.Album.ImageRemove.Guide.Success": ["Delete image successful.", "画像を削除に成功しました。"],
    "PickList.Album.ImageRemove.Guide.Failed": ["Delete image failed.", "画像を削除に失敗しました。"],
    "PickList.Album.Import.Title": ["Import new image file", "新しい画像の取り込み"],
    "PickList.Album.Import.Guide": ["Import new image file", "子フォルダを開くには、ダブルクリック"],
    
    
    // "Advertise.Deploy.Menu.Exit": ["Send", "配信"],
    "Advertise.Deploy.Menu.Exit": ["Send", "終了"],
    /*"Advertise.Deploy.Menu.Button.FileSave": ["Cancel", "配信せず<br>中止"],*/
    "Advertise.Deploy.Menu.Button.FileSave": ["Cancel", "終了"],
    "Advertise.Deploy.Menu.Button.FileUndo": ["Undo", "元に戻す"],
    "Advertise.Deploy.Menu.Button.TaskCreate": ["New Task", "新規予定"],
    "Advertise.Deploy.Menu.Button.TaskDelete": ["Delete", "削除する"],
    "Advertise.Deploy.Menu.Button.TaskObsolete": ["Task Obsolete", "適用終了"],
    "Advertise.Deploy.Menu.Button.TaskUpdate": ["Update", "変更する"],
    "Advertise.Deploy.Menu.Button.Address": ["Targets", "適用先一覧"],
    "Advertise.Deploy.Menu.Button.CollectLogs": ["Collect Logs", "更新"],
    "Advertise.Deploy.Menu.Question.Undo": ["The deployment schedule is being reverted.<br>You changes will be lost.<br><br>Are you sure?",
                                            "全ての予定を元に戻します。<br>変更した内容は失われます。<br><br>よろしいですか。"],
//  "Advertise.Deploy.Menu.Question.Exit": ["To abort without delivering.<br>Edited data will be deleted<br><br><br>Are you sure?",
//                                          "配信せず中止します。<br>編集データは削除されます。<br><br>よろしいですか。"],
    "Advertise.Deploy.Menu.Question.Exit": ['To exit without delivery.<br><br>Edited data will be saved.<br>To deliver later, please press the "Resen" of home.<br><br>Are you sure you want or to abort.', "配信せずに終了します。<br><br>編集データは保存されます。<br>後で配信するには、ホームの「再配信」を押してください。<br><br>中止してよろしいですか。"],
    "Advertise.Deploy.Menu.Question.Remove": ["The task is being deleted.<br><br><br>Are you sure?",
                                            "選択された予定を削除します。<br><br>よろしいですか。"],

    "Advertise.Deploy.Menu.Question.RemoveToObsolete": ["Remove the task to obsolete.<br><br><br>Are you sure?", "選択された予定を適用終了します。<br><br>よろしいですか。"],
    "Advertise.Deploy.Menu.Feedback.Save.Successful": ["The schedule was successfully saved.","構成適用予定が、保存されましたが。<br>配信されていません。"],
    "Advertise.Deploy.Menu.Feedback.Save.Failed": ["Failed to save the schedule.<br>Please check the server connection","構成適用予定を保存できませんでした。<br>接続を確認してください。"],
    "Advertise.Deploy.Menu.Feedback.InvokeTransfer.Successful": ["The schedule start transfer successfully.","構成の配信が開始されました。"],
    "Advertise.Deploy.Menu.Feedback.InvokeTransfer.Failed": ["Failed to start transfer the schedule.<br>Please check the server connection","構成の配信が開始できませんでした。<br>接続を確認してください。"],
    "Advertise.Deploy.Menu.Okay": ["OK","確認"],
    "Advertise.Deploy.Menu.No": ["No","いいえ"],
    "Advertise.Deploy.Menu.Yes": ["Yes","はい"],
    "Advertise.Deploy.Directory.Title": ["Configurations","構成一覧"],
    "Advertise.Deploy.Directory.advertise": ["Advertise Items","広告商品"],
    "Advertise.Deploy.Directory.pickList": ["Unnumbered Items","バーコードのない商品"],
    "Advertise.Deploy.Directory.notices": ["Operational Notice","業務連絡"],
    "Advertise.Deploy.Directory.options": ["Advanced Options","詳細設定"],
    "Advertise.Deploy.Directory.usability": ["Usability Settings","操作画面構成"],
    "Advertise.Deploy.Directory.effective": ["Deployed","適用中"],
    "Advertise.Deploy.Directory.scheduled": ["To Deploy","適用待ち"],
    "Advertise.Deploy.Directory.obsolete": ["Obsolete","適用終了"],
    "Advertise.Deploy.Directory.draft": ["Draft","下書き"],
    "Advertise.Deploy.Tasks.To": ["To: ","対象： "],
    "Advertise.Deploy.Tasks.Total": ["Total:","対象数:"],
    "Advertise.Deploy.Tasks.Remaining": ["Left:","未開封:"],
    "Advertise.Deploy.Tasks.Expire": ["Expire on:","有効期限:"],
    "Advertise.Deploy.Tasks.Expire.Obsolete": ["Expire Obsolete:","適用終了"],
//  "Advertise.Deploy.Tasks.ToApply": ["To Apply:","未適用:"],
//  "Advertise.Deploy.Tasks.ToOpen": ["To Open:","未開封:"],
    "Advertise.Deploy.Okay": ["OK", "確定"],
    "Advertise.Deploy.Void": ["Void", "取消"],
    "Advertise.Deploy.Yes": ["Yes", "はい"],
    "Advertise.Deploy.No": ["No", "いいえ"],
    "Advertise.Deploy.deleteOrVoid": ["Remove the store", "店舗を削除しますか"],
    "Advertise.Deploy.confirmMessage": ["Would you like to delivery", "配信しますか"],
    "Advertise.Deploy.Cancel": ["Cancel", "中止"],
    "Advertise.Deploy.EditTask.Guide": ["Please select an item to deploy.","適用する構成を選択して下さい。"],
//  "Advertise.Deploy.EditTask.ToDeploy": ["To Deploy:","配信する"],
    "Advertise.Deploy.EditTask.Draft": ["Draft:","下書き"],
    "Advertise.Deploy.EditTask.Target": ["Deploy To","適用店舗"],
    "Advertise.Deploy.EditTask.Date": ["Deploy on","適用日付"],
    "Advertise.Deploy.EditTask.Time": ["Deploy at","適用時刻"],
    "Advertise.Deploy.EditTask.YYYYMMDD": ["YYYYMMDD","YYYYMMDD"],
    "Advertise.Deploy.EditTask.HHMM": ["HHMM","HHMM"],
    "Advertise.Deploy.EditTask.DeployTimeHour": ["Hour","時"],
    "Advertise.Deploy.EditTask.DeployTimeMinute": ["Minute","分"],
    "Advertise.Deploy.EditTask.DeployTimeUp": ["▲","▲"],
    "Advertise.Deploy.EditTask.DeployTimeDown": ["▼","▼"],
//  "Advertise.Deploy.DetailView.ViewTital": ["Left Stores","未開封の店舗"],
    "Advertise.Deploy.DetailView.ViewTital": ["Left store detail ","未開封店舗一覧"],
    "Advertise.Deploy.DetailView.ViewSave": ["Save to csv file","ＣＳＶへ出力"],
    "Advertise.Deploy.DetailView.StoreID": ["Store ID","店舗番号"],
    "Advertise.Deploy.DetailView.StoreName": ["Japanese Name","店舗名"],
//  "Advertise.Deploy.DetailView.StoreName": ["Japanese Name","日本語名"],
    "Advertise.Deploy.DetailView.StoreTel": ["Telphone number","電話番号"],

    "Advertise.Deploy.EditStore": ["Edit Store","店舗編集"],
    "Advertise.Deploy.EditStore.Guide": ["Please Edit Store or Store Group","適用先を編集します"],
    "Advertise.Deploy.EditStore.SearchStore": ["Store numbers/Japanese name","店舗番号/店舗名 で検索"],
    "Advertise.Deploy.AddStore": ["Add Store","新規店舗"],
    "Advertise.Deploy.AddStoreGroup": ["Add Store Group","新規店舗グループ"],
    "Advertise.Deploy.EditStoreGroup": ["Edit Store Group","店舗グループ編集"],

    "Advertise.Deploy.AddStore.Guide":["Please Edit Store","店舗を編集します"],
    "Advertise.Deploy.DeleteStore":["Delete","削除"],
    "Advertise.Deploy.AddStore.storeId":["StoreId","店舗番号"],
    "Advertise.Deploy.AddStore.storeEnName":["En Name","英語名"],
    "Advertise.Deploy.AddStore.storeJaName":["Ja Name","店舗名"],
//  "Advertise.Deploy.AddStore.storeJaName":["Ja Name","日本語名"],
//  "Advertise.Deploy.AddStore.storeIP":["IP address","正サーバIP"],
    "Advertise.Deploy.AddStore.storeIP":["IP address","プライマリ店舗サーバーIP"],
    "Advertise.Deploy.AddStore.storeIPDetail":["IP address","プライマリーIP"],
    "Advertise.Deploy.AddStore.storeSecondaryIP":["IP address","セカンダリ店舗サーバーIP"],
    "Advertise.Deploy.AddStore.storeSecondaryIPDetail":["IP address","セカンダリIP"],
//  "Advertise.Deploy.AddStore.storeSecondaryIP":["IP address","副サーバIP"],
    "Advertise.Deploy.AddStore.storeTel":["Telephone number","電話番号"],
    "Advertise.Deploy.AddStore.success":["add store success","店舗追加しました"],
    "Advertise.Deploy.AddStore.exist":["the store exits","店舗既にあります"],
    "Advertise.Deploy.AddStore.failed":["failed to add the store","店舗追加失敗"],
    "Advertise.Deploy.AddStore.emptyId":["failed to add the store!storeID can not be empty","店舗番号を空にできません"],
    "Advertise.Deploy.AddStore.ExistStoreId":["failed to add the store!the　storeID is already exist","この店舗番号はすでに存在しております"],
    "Advertise.Deploy.AddStore.isNotNum":["failed to add the store!storeID must be digits","店舗番号は数字のみ"],
    "Advertise.Deploy.AddStore.emptyNmEn":["failed to add the store!English name can not be empty","英語名は空にできません"],
    "Advertise.Deploy.AddStore.emptyNmJp":["failed to add the store!Japanese name can not be empty","店舗名は空にできません"],
    "Advertise.Deploy.AddStore.emptyIP":["failed to add the store!primary　IP address can not be empty","プライマリ店舗サーバーIPアドレスは空にできません"],
    "Advertise.Deploy.AddStore.errorIP":["failed to add the store!primary　IP address format is incorrect","プライマリ店舗サーバーIPアドレスの形式が正しくありません"],
    "Advertise.Deploy.AddStore.emptySecondaryIP":["failed to add the store!Secondary　IP address can not be empty","セカンダリ店舗サーバーIPアドレスは空にできません"],
    "Advertise.Deploy.AddStore.errorSecondaryIP":["failed to add the store!Secondary　IP address format is incorrect","セカンダリ店舗サーバーIPアドレスの形式が正しくありません"],
    "Advertise.Deploy.AddStore.emptyTel":["failed to add the store!Telephone number can not be empty","電話番号は空にできません"],
    "Advertise.Deploy.AddStore.errorTel":["failed to add the store!Telephone number format is incorrect","電話番号の形式が正しくありません"],

    "Advertise.Deploy.UpdateStore.success":["update store success","店舗変更しました"],
    "Advertise.Deploy.UpdateStore.failed":["failed to update the store","店舗変更失敗"],

    "Advertise.Deploy.DeleteStore.success":["delete store success","店舗削除しました"],
    "Advertise.Deploy.DeleteStore.failed":["failed to delete the store","店舗削除失敗"],

    "Advertise.Deploy.AddStoreGroup.Guide":["Please Edit Store Group","店舗グループ編集"],
    "Advertise.Deploy.AddStoreGroup.storeGroupName":["Store Group Name","店舗グループ名"],
    "Advertise.Deploy.AddStoreGroup.doAdd":["Add","追加"],
    "Advertise.Deploy.AddStoreGroup.doDelete":["Delete","削除"],
//  "Advertise.Deploy.AddStoreGroup.toRight":["→","→"],
//  "Advertise.Deploy.AddStoreGroup.toLeft":["←","←"],

    "Advertise.Deploy.AddStoreGroup.success":["add store success","店舗グループ追加しました"],
    "Advertise.Deploy.AddStoreGroup.exist":["the store exits","店舗グループ既にあります"],
    "Advertise.Deploy.AddStoreGroup.failed":["failed to add the store","店舗グループ追加失敗"],

//  "Advertise.Deploy.AddStoreGroup.storeGroupNameEn":["StoreGroup En Name","店舗グループ英語名"],
//  "Advertise.Deploy.AddStoreGroup.storeGroupNameJa":["StoreGroup Ja Name","店舗グループ日本名"],
    "Advertise.Deploy.AddStoreGroup.storeGroupNameJa":["StoreGroup Ja Name","店舗グループ名"],
    "Advertise.Deploy.AddStoreGroup.emptyGroupNameJa":["failed to add the store group! Japanese name can not be empty.","店舗グループ名は空にできません"],

    "Advertise.Deploy.AddStoreGroup.storeEntryLTOR":["Store entry list view","店舗一覧"],
    "Advertise.Deploy.AddStoreGroup.storeEntryRTOL":["Store group list view","店舗グループ"],

    "Advertise.Deploy.UpdateStoreGroup.success":["update store success","店舗変更しました"],
    "Advertise.Deploy.UpdateStoreGroup.failed":["failed to update the store","店舗変更失敗"],

    "Advertise.Deploy.DeleteStoreGroup.success":["delete store success","店舗グループ削除しました"],
    "Advertise.Deploy.DeleteStoreGroup.failed":["failed to delete the store","店舗グループ削除失敗"],

    "Advertise.Deploy.Warning.missingTarget":["Targeted stores are not selected.","「適用店舗」が選択されていません。"],
    "Advertise.Deploy.Warning.invalidDateTime":["Date/Time is invalid.","無効な日付または時刻です。"],
    "Advertise.Deploy.Warning.passedDateTime":["The date/time already passed.","入力された日時は、既に過ぎています。"],
    "Advertise.Deploy.Warning.missingFile":["config file is not selected.","配信する構成が選択されていません。"],

    "Advertise.Deploy.FileExplorer.Title.Exmport": ["Exmport to new file", "出力先を選択"],
    "Advertise.Deploy.FileExplorer.Button.CsvSave":["Save", "保存"],
    "Advertise.Deploy.FileExplorer.Button.Back" :["Back","戻る"],
    "Advertise.Deploy.FileExplorer.Button.Cancel" :["Cancel","中止"],
    "Advertise.Deploy.FileExplorer.Button.Open" :["Open","開く"],
    "Advertise.Deploy.FileExplorer.FileName.Name" :["File Name","ファイル名"],
    "Advertise.Deploy.FileExplorer.FileName.Length" :["Up to 50 characters", "最大全角25文字"],

    "Advertise.Deploy.SaveDetail.FileEntry" :["File Path:", "ファイルパス："],
    "Advertise.Deploy.SaveDetail.Button.Back":["Back", "戻る"],
    "Advertise.Deploy.SaveDetail.Button.CsvSave":["Save", "保存"],
    "Advertise.Deploy.SaveDetail.Button.Cancel" :["Cancel","中止"],
    "Advertise.Deploy.SaveDetail.Button.Confirm" :["Confirm","確定"],

    "Advertise.Deploy.SaveDetail.Success.Notice" :["File saving is completed!", "ファイルを保存しました！"],
    "Advertise.Deploy.SaveDetail.Exist.Overwrite": ["Overwrite existing file", "同名の既存ファイルがあれば上書きする"],
    "Advertise.Deploy.SaveDetail.Exist.Notice": ["File with the same name already exists!<br>Please change the file name, or turn on the overwrite option above.",
                                                "同じ名前のファイルがすでに存在します！<br>名前を変更するか、上の上書きオプションをオンにしてください。"],
    "Advertise.Deploy.SaveDetail.Warning.IsEmptyName": ["Please fill in the file name.", "ファイル名を入力してください。"],
    "Advertise.Deploy.SaveDetail.Warning.InValidName": ["Please fill in the file name a valid file name.", "ファイル名を正しく入力してください。"],
    "Advertise.Deploy.SaveDetail.Warning.IsLengthOver": ["Please fill in the file name 50 characters.", "ファイル名を全角25文字以下に入力してください。"],
    "Advertise.Deploy.SaveDetail.Error.Notice" :["Access denied. <br>You do not have permission to save in this location. <br>Please get the permission to contact the administrator.",
                                                "アクセスが拒否されました。<br><br>この場所に保存するアクセス許可がありません。<br>管理者に連絡してアクセス許可を取得してください。"],


    "Advertise.Album.Menu.Exit":["Exit", "終了"],
    "Advertise.Album.Menu.ImageList" :["Image List","画像一覧"],
    "Advertise.Album.Menu.ImageImportPart" :["Import","画像<br>取り込み<br>600*640"],
    "Advertise.Album.Menu.ImageImportFull" :["Import","画像<br>取り込み<br>1020*640"],
    "Advertise.Album.Menu.ImageDelete" :["Delete Image","画像<br>削除"],
    "Advertise.Album.Button.ImageCopyStart":["Import", "取り込む"],
    "Advertise.Album.Button.Back" :["Back","戻る"],
    "Advertise.Album.Button.Cancel" :["Cancel","中止"],
    "Advertise.Album.Button.Delete" :["Delete","削除"],
    "Advertise.Album.Button.DeleteAgain" :["Delete Again","再削除"],
    "Advertise.Album.Button.Confirm" :["Confirm","確定"],
    "Advertise.Album.Button.Open" :["Open","開く"],
    "Advertise.Album.Button.Yes": ["Yes", "はい"],
    "Advertise.Album.Button.No": ["No", "いいえ"],
    "Advertise.Album.EditImage.Recursive" :["CopySubFolder","子フォルダ含め"],
    "Advertise.Album.lblFolderFrom" :["Copy File From:","処理対象フォルダ:"],
    "Advertise.Album.lblFolderTo" :["Copy File To:","コピー先:"],
    "Advertise.Album.ImportSuccess": ["Image import successful.", "画像取り込みに成功しました。"],
    "Advertise.Album.ImportFailed": ["Image import failed.", "画像取り込みに失敗しました。"],
    "Advertise.Album.ImageList.Guide.Images": ["Image List", "画像一覧"],
    "Advertise.Album.ImageList.ComingSoon": ["Coming Soon", "準備中"],
//  "Advertise.Album.ImageRemove.Guide": ["Selected file will be removed.<br> Are you sure.", "ファイルを削除します。<br>よろしいですか。"],
    "Advertise.Album.ImageRemove.Guide.Confirm": ["The currently selected image has been applied to the product image.<br><br>Are you sure to delete the image?", "選択中の画像は商品画像に適用されています。<br><br>画像を削除しますか。"],
    "Advertise.Album.ImageRemove.Guide.Success": ["Delete image successful.", "画像を削除に成功しました。"],
    "Advertise.Album.ImageRemove.Guide.Failed": ["Delete image failed.", "画像を削除に失敗しました。"],
    "Advertise.Album.Import.Title": ["Import new image file", "新しい画像の取り込み"],
    "Advertise.Album.Import.Guide": ["Import new image file", "子フォルダを開くには、ダブルクリック"],

    "Settings.Button.Change": ["Change","変更"],
    "Settings.TableOfContents.Title": ["Settings", "各種設定"],
    "Settings.TableOfContents.Device": ["Device Settings", "端末設定"],
    "Settings.TableOfContents.Printer": ["Printer Settings", "プリンター設定"],
    "Settings.TableOfContents.Transfer": ["Transfering Data", "他の端末との連動"],
    "Settings.TableOfContents.Personal": ["Personal Settings", "個人設定"],
    "Settings.TableOfContents.Software": ["Software", "ソフトウェア"],
    "Settings.Device.Title": ["Device Settings", "端末設定"],
    "Settings.Device.Back": ["Back", "戻る"],
    "Settings.Device.OtherCompany": ["Other Company (10 Key)", "その他の企業（番号手入力)"],
    "Settings.Device.CompanyID": ["Company ID", "企業番号"],
    "Settings.Device.CompanyID.Title": ["Company ID", "企業番号"],
    "Settings.Device.StoreID": ["Store ID", "店舗番号"],
    "Settings.Device.StoreID.Title": ["Store ID", "店舗番号"],
    "Settings.Device.WorkstationID": ["Terminal ID", "レジ番号・端末番号"],
    "Settings.Device.WorkstationID.Title": ["Terminal ID", "レジ番号・端末番号"],
    "Settings.Device.Language": ["Language", "言語(Language)"],
    "Settings.Device.Language.Title": ["Language", "言語"],
    "Settings.Device.Language.en": ["English", "英語(English)"],
    "Settings.Device.Language.ja": ["Japanese", "日本語(Japanese)"],
//  "Settings.Device.Restart": ["Restart", "再起動"],
//  "Settings.Device.Restart": ["Set", "設定"],
    "Settings.Device.Restart": ["Restart", "設定終了"],
    "Settings.Device.RestartOpen": ["ReOpen", "開始"],
    "Settings.Device.Cursor": ["Show mouse pointer", "マウスポインターを表示"],
    "Settings.Device.Volume": ["Volume", "音量"],
    "Settings.Device.Deregister": ["Deregister", "登録解除"],
    "Settings.Software.Core": ["internal Log", "内部ログ"],
    "Settings.Software.Restore": ["Restore", "再読込み"],
    "Settings.Software.Close": ["Exit", "終了"],
    "Settings.Printer.Title": ["Please select printer", "接続するプリンターを選択してください。"],
    "Settings.Transfer.Title": ["Please select target device", "接続する端末を選択してください。"],
    "Settings.Personal.Title": ["Change Password", "パスワード変更"],
    "Settings.Personal.OldPassword": ["Old Password", "旧パスワード"],
    "Settings.Personal.NewPassword": ["New Password", "新パスワード"],
    "Settings.Personal.ReEnter": ["ReEnter", "再入力"],
    "Settings.Personal.Training": ["Training mode", "トレーニングモード"],

    "HiddenTool.": ["", ""],
    "HiddenTool.Close": ["Close", "閉じる"],
    "HiddenTool.Maintenance": ["Maintenance", "保守"],
    "HiddenTool.MagneticCard": ["MagneticCard", "磁気カード"],
    "HiddenTool.BarCode": ["BarCode", "バーコード"],
    "HiddenTool.EMoney": ["eMoney", "電子マネー"],
    "HiddenTool.BillDispenser": ["Bill Dispenser", "釣銭機"],
    "HiddenTool.Test": ["Test", "テスト"],
    "HiddenTool.Reload": ["Reload", "再起動"],
    "HiddenTool.Terminate": ["Terminate", "強制終了"],
    "HiddenTool.MessageLog": ["Msg Log", "内部ログ"],
    "HiddenTool.ScanID": ["Scan ID", "扱者スキャン"],
    "HiddenTool.Membership": ["Membership", "会員番号"],
//  "HiddenTool.Membership": ["Membership", "オーナーズカード"],
    "HiddenTool.SwipeCredit": ["Credit Card", "クレジットカード"],
    "HiddenTool.GiftCard": ["Gift Card", "ギフトカード"],
    "HiddenTool.Waon": ["WAON", "WAON"],
    "HiddenTool.Id": ["iD", "iD"],
    "HiddenTool.QuicPay": ["QuicPay", "QuicPay"],
    "HiddenTool.Suica": ["Suica", "Suica"],
    "HiddenTool.Pasmo": ["Pasmo", "Pasmo"],
    "HiddenTool.ScanItem": ["Scan Item", "商品スキャン"],
    "HiddenTool.GiftCertificate": ["Gift Certificate","商品券"],
    "HiddenTool.Voucher": ["Voucher","金券"],
    "HiddenTool.CatalinaCoupon": ["Coupon (Catalina)","クーポン券(カタリナ)"],
    "HiddenTool.MomCoupon": ["Coupon (Mom)","クーポン券(MOM)"],
    "HiddenTool.Receipt": ["Receipt","レシート"],
    "HiddenTool.Custanet": ["Custanet","かざすクーポン"],
    "HiddenTool.CashDeposit": ["Deposit", "入金"],
    "HiddenTool.CashDispense": ["Dispense", "出金"],
    "HiddenTool.CashRead": ["Cash Read", "現金読取"],
    "HiddenTool.WaitPage": ["Wait Page", "待受画面"],

    "HiddenTool.Bills10k": ["$100 bills","10,000円"],
    "HiddenTool.Bills5k": ["$50 bills","5,000円"],
    "HiddenTool.Bills1k": ["$10 bills","1,000円"],
    "HiddenTool.Coins500": ["$5.00","500円"],
    "HiddenTool.Coins100": ["$1.00","100円"],
    "HiddenTool.Coins50": ["$0.50","50円"],
    "HiddenTool.Coins10": ["$0.10","10円"],
    "HiddenTool.Coins5": ["$0.05","5円"],
    "HiddenTool.Coins1": ["$0.01","1円"],
    "HiddenTool.Multiple1": ["x1","x1"],
    "HiddenTool.Multiple10": ["x10","x10"],

    "Home.Welcome": ["Welcome, ", "ようこそ"],
    "Home.PickList": ["Unnumbered Items","バーコードのない商品"],
    "Home.PickListEdit": ["Unnumbered Items","編集"],
    "Home.PickListDeploy": ["Unnumbered Items","適用予定"],
    "Home.PickListReTransfer": ["Unnumbered Items","再配信"],
//  "Home.PickList": ["Unnumbered Items","バーコードのない商品"],
    "Home.Notice": ["Operational Notices","業務連絡" ],
    "Home.Notices": ["Notices","業務連絡" ],
    "Home.Advertises": ["Advertises","広告" ],
    "Home.AdvertiseDeploy": ["Operational Advertises","適用予定" ],
    "Home.AdvertiseEdit": ["Operational Advertises","編集" ],
    "Home.NoticesEdit": ["Operational Notices","編集" ],
    "Home.NoticesDeploy": ["Operational Notices","適用予定" ],
    "Home.NoticesReTransfer": ["Operational Notices","再配信" ],
    "Home.Options": ["Advanced Options","詳細設定" ],
    "Home.Usability": ["Usability Settings","操作画面構成" ],
//  "Home.Deploy": ["Deployment Schedule","構成適用予定"],
//  "Home.Transfer": ["Emergency deploy","再配信"],
    "Home.okayOrVoid": ["Would you like to emergency deploy","配信しますか"],
    "Home.Okay": ["OK", "確定"],
    "Home.Void": ["Void", "取消"],
    // 2014/09/12 Lee Add
//  "Home.ImageCopy":["Copy&Resize ImageFiles","画像コピー&加工"],
    "Home.ImageCopy":["Image management","画像整理"],
    "Home.DemoSetUp":["Demo SetUp","デモファイルコピー"],

//  "ImageCopy.Menu.Exit":["Exit", "終了"],
//  "ImageCopy.Menu.ImageList" :["Image List","画像一覧"],
//  "ImageCopy.Menu.ImageImport" :["Import","画像<br>取り込み"],
//  "ImageCopy.Menu.ImageDelete" :["Delete Image","画像<br>削除"],
//  "ImageCopy.Button.ImageCopyStart":["Import", "取り込む"],
//  "ImageCopy.Button.Back" :["Back","戻る"],
//  "ImageCopy.Button.Cancel" :["Cancel","中止"],
//  "ImageCopy.Button.Open" :["Open","開く"],
//  "ImageCopy.Button.Yes": ["Yes", "はい"],
//  "ImageCopy.Button.No": ["No", "いいえ"],
//  "ImageCopy.EditImage.Recursive" :["CopySubFolder","子フォルダ含め"],
//  "ImageCopy.lblFolderFrom" :["Copy File From:","処理対象フォルダ:"],
//  "ImageCopy.lblFolderTo" :["Copy File To:","コピー先:"],
//  "ImageCopy.ImportSuccess":  ["Image import successful.", "画像取り込みに成功しました。"],
//  "ImageCopy.ImportFailed":   ["Image import failed.", "画像取り込みに失敗しました。"],
//  "ImageCopy.ImageList.Guide.Images": ["Image List", "画像一覧"],
//  "ImageCopy.ImageList.ComingSoon": ["Coming Soon", "準備中"],
//  "ImageCopy.FileRemove.Guide": ["Selected file will be removed.<br> Are you sure.", "ファイルを削除します。<br>よろしいですか。"],
//  "ImageCopy.Import.Title": ["Import new image file", "新しい画像の取り込み"],
//  "ImageCopy.Import.Guide": ["Import new image file", "子フォルダを開くには、ダブルクリック"],

    "KeyPad.Clear": ["Clear","消す"],
//  "KeyPad.Department": ["Dept","部門"],
    "KeyPad.BS": ["BS","1字削除"],
    "KeyPad.Enter": ["Enter","登録"],
    "KeyPad.Next": ["Next","次へ"],
    "KeyPad.Search": ["Search","検索"],

    "NavigationBar.Title.undefined": ["Closed", "準備中"],
    "NavigationBar.Title.credential": ["Log In","扱者入力" ],
//  "NavigationBar.Title.home": ["UI Configurator","画面構成・配信ツール" ],
    "NavigationBar.Title.home": ["UI Configurator","ホーム" ],
    "NavigationBar.Title.deploy": ["Deployment ","構成適用予定" ],
//  "NavigationBar.Title.pickList": ["Unnumbered Items","バーコードのない商品" ],
    "NavigationBar.Title.pickListEditor": ["Unnumbered Items Editor","バーコードのない商品・編集" ],
    "NavigationBar.Title.pickListDeploy": ["Unnumbered Items Deploy","バーコードのない商品・適用予定" ],
    "NavigationBar.Title.pickListAlbum": ["Unnumbered Image Album","バーコードのない商品・画像整理" ],
//  "NavigationBar.Title.notice": ["Operation Notices","業務連絡" ],
    "NavigationBar.Title.noticesEditor": ["Operation Notices Editor","業務連絡・編集" ],
    "NavigationBar.Title.noticesDeploy": ["Operation Notices Deploy","業務連絡・適用予定" ],
    "NavigationBar.Title.noticesAlbum": ["Operation Image Album","業務連絡・画像整理" ],
    "NavigationBar.Title.options": ["Advanced Options","詳細設定" ],
    "NavigationBar.Title.usability": ["Usability Settings","操作画面構成" ],
    "NavigationBar.Title.settings":     ["Settings","各種設定" ],
//          "NavigationBar.StoreId":    ["Store#: ", "店舗番号: "],
//          "NavigationBar.TermId": ["Term#: ", "レジ番号: "],
//          "NavigationBar.UserId": ["User: ", "担当者: "],

//  "NavigationBar.Title.imagecopy":    ["Copy&Resize ImageFiles","画像コピー&加工"],
    "NavigationBar.Title.imagecopy":    ["Image management","画像整理"],
    "NavigationBar.Title.advertisementEditor": ["Advertisement Editor","広告・編集"],
    "NavigationBar.Title.advertisementAlbum": ["Advertisement Album","広告・画像整理"],
    "NavigationBar.Title.advertisementDeploy": ["Advertisement Deploy","広告・適用予定"],
    
    "Notice.Button.Yes": ["Yes", "はい"],
    "Notice.Button.No": ["No", "いいえ"],
    "Notice.Button.Save": ["Save", "保存"],
    "Notice.Button.Okay": ["OK", "確認"],
    "Notice.Button.Open": ["Open", "開く"],
    "Notice.Button.Create": ["Create", "作成"],
    "Notice.Button.Back": ["Back", "戻る"],
    "Notice.Button.Submit": ["Submit", "確定"],
    "Notice.Button.Apply": ["Apply", "適用"],
    "Notice.Button.Cancel": ["Cancel", "中止"],
    "Notice.Button.Import": ["ImportImage", "画像取込"],
    "Notice.Cancel": ["Cancel", "中止"],
    "Notice.Delete": ["Submit", "削除"],
    "Notice.Okay": ["OK", "確定"],
    "Notice.Menu.Exit": ["Exit", "終了"],
    "Notice.Menu.FileCreate": ["Create", "新規作成"],
    "Notice.Menu.FileOpen": ["Open", "開く"],
    "Notice.Menu.FileSave": ["Save", "保存"],
    "Notice.Menu.FileClose": ["Cancel", "中止"],
    "Notice.Menu.FileAttach":["Attach","画像添付"],
    "Notice.Menu.AttachmentDelete":["Delete","添付削除"],
    "Notice.Menu.DateClear":["Date Clear","無期限"],
    //zhuxingnuo--begin
    "Notice.Menu.FilePrint":["FilePrint","印刷"],
    "Notice.MenuFilePrint.FileName":["FileName","ファイル名:"],
    "Notice.MenuFilePrint.FileName1":["Tab Line1:","タブ1行目:"],
    "Notice.MenuFilePrint.FileName2":["Tab Line2:","タブ2行目:"],
    "Notice.MenuFilePrint.Expiry":["Expiry:","有効期限:"],
    "Notice.MenuFilePrint.Content":["Content:","内容:"],
    "Notice.MenuFilePrint.Picture":["Picture:","イメージ:"],
    //zhuxingnuo--end
    "Notice.Menu.FileImport": ["Import", "読み込み"],
    "Notice.Menu.FileName": ["Tab Line1:", "タブ1行目:"],
    "Notice.Menu.FileName2": ["Tab Line2:", "タブ2行目:"],
    "Notice.Menu.Expiry": ["Expiry:", "有効期限:"],
    "Notice.Menu.FileRemove": ["Remove", "削除"],
    "Notice.Menu.MaxLength10": ["Up to 10 characters:", "最大全角10文字:"],
    "Notice.ItemList.FileList": ["File List", "保存ファイル一覧"],
    "Notice.FileCreate.FileName": ["New Title", "新規 題名"],
    "Notice.FileCreate.NameLength": ["Up to 50 characters", "最大全角25文字"],
    "Notice.FileCreate.Guide": ["You are making a new file.<br>Please enter your file name.", "新しいファイルの名前を入力してください。"],
    "Notice.FileCreate.InputEmptyName": ["Please fill in the file name.", "ファイル名を入力してください。"],
    "Notice.FileCreate.InValidName": ["Please fill in the file name a valid file name.", "ファイル名を正しく入力してください。"],
    "Notice.FileCreate.FileNameLengthOver": ["Please fill in the file name 50 characters.", "ファイル名を全角25文字以下にしてください。"],
    "Notice.FileOpen.Guide": ["Please select a configuration file to open", "開くファイルを選択してください"],
//  "Notice.FileSave.Guide": ["The file is being saved.<br>Are you sure?", "ファイルを保存します。<br>よろしいですか。"],
//  "Notice.FileSave.Guide.StatusInput": ["Please input the file name for uploading.", "保存するファイル名を入力してください"],
    "Notice.FileSave.Title": ["Save File", "ファイルの保存"],
    "Notice.FileSave.Guide": ["Please input the file name for uploading.", "保存するファイル名を入力してください"],
    "Notice.FileSave.Overwrite": ["Overwrite existing file", "同名の既存ファイルがあれば上書きする"],
    "Notice.FileSave.AlreadyExists": ["File with the same name already exists!<br>Please change the file name, or turn on the overwrite option above.", "同じ名前のファイルがすでに存在します！<br>名前を変更するか、上の上書きオプションをオンにしてください。"],
    "Notice.FileSave.Guide.StatusSuccessful": ["File saving is completed!", "ファイルを保存しました！"],
    "Notice.FileSave.Guide.StatusFailed": ["File saving is failed!", "ファイルを保存失敗しました！"],
    "Notice.FileSave.FileId": ["Filename", "ファイル名"],
    "Notice.FileSave.InputEmptyName": ["Please fill in the file name.", "ファイル名を入力してください。"],
    "Notice.FileSave.InValidName": ["Please fill in the file name a valid file name.", "ファイル名を正しく入力してください。"],
    "Notice.FileSave.FileNameLengthOver": ["Please fill in the file name 50 characters.", "ファイル名を全角25文字以下にしてください。"],
    "Notice.FileSave.NameLength": ["Up to 50 characters", "最大全角25文字"],
    "Notice.FileRemove.Guide": ["Selected file will be removed.<br> Are you sure.", "ファイルを削除します。<br>よろしいですか。"],
    "Notice.FileClose.Guide": ["The file is being closed.<br>Are you sure?", "ファイルを閉じます。<br>よろしいですか。"],
    "Notice.FileClose.AlreadyChanged": ["The file was changed, to save and close it before?", "ファイルは変更されています。<br><br>保存せずに、ファイルを閉じますか。"],
    "Notice.Guide.Images": ["Please select the image", "画像を選択してください"],
    "Notice.ImageEmpty":["There is no images.", "画像ファイルがありませんでした."],
    "Notice.Failure.menu.missingTab":["Please entry the 1st line of the tab", "タブ1行目を入力してください。"],
    "Notice.Failure.menu.tab1limit":["Please make the 1st line of the tab up to 20 characters.", "タブ1行目を、最大全角10文字にしてください。"],
    "Notice.Failure.menu.tab2limit":["Please make the 2nd line of the tab up to 20 characters.", "タブ2行目を、最大全角10文字にしてください。"],
    "Notice.Failure.menu.invalidDate":["Invalid expire date.<br>Please check it again.", "有効期限の日付が無効です。<br>もう一度確認してください。"],
//  "Notice.Failure.notices.scheduled":["Can not delete ,File is used in deploy.", "削除できません。<br>適用が予定されているか、現在適用中です。"],
    "Notice.Failure.notices.scheduled":["It is currently being applied. <br>If you want to delete, please delivery by setting the expiration date to a past date..",
                                                                            "現在適用中です。<br>削除する場合は、有効期限を過去の日付に設定して配信してください。"],
    "Notice.Popup.OK": ["OK", "確認"],

    "PickList.Button.Yes": ["Yes", "はい"],
    "PickList.Button.No": ["No", "いいえ"],
    "PickList.Button.Okay": ["OK", "確認"],
    "PickList.Button.Open": ["Open", "開く"],
    "PickList.Button.Create": ["Create", "作成"],
    "PickList.Button.Save": ["Save", "保存"],
    "PickList.Button.Cancel": ["Cancel", "中止"],
    "PickList.Button.Import": ["ImportImage", "画像取込"],
    "PickList.Button.Delete": ["Delete", "削除"],
    "PickList.Back": ["Back", "戻る"],
    "PickList.Submit": ["Submit", "確定"],
    "PickList.Apply": ["Apply", "適用"],
    "PickList.Void": ["Void", "取消<br>(元に戻す)"],
    "PickList.Delete": ["Delete", "削除"],
    "PickList.Menu.Exit": ["Exit", "終了"],
    "PickList.Menu.FileCreate": ["Create", "新規作成"],
    "PickList.Menu.FileOpen": ["Open", "開く"],
    "PickList.Menu.FileRemove": ["Remove", "削除"],
    "PickList.Menu.FileSave": ["Save", "保存"],
    "PickList.Menu.FileClose": ["Cancel", "中止"],
    "PickList.Menu.FileImport": ["Import", "読み込み"],
    "PickList.Menu.FileName": ["File:", "ファイル名:"],
    "PickList.Menu.EditItems": ["Items", "商品一覧"],
    "PickList.Menu.EditCategories": ["Categories", "分類"],
    "PickList.Menu.EditLayout": ["Layout", "画面配置"],
    "PickList.Menu.FilePrint": ["Print", "印刷"],
    "PickList.Menu.ClearTabItems": ["Clear items", "全クリア"],
    "PickList.FilePrint.FileName":  ["FileName", "ファイル名："],
    "PickList.FilePrint.ItemId":  ["Item Code", "商品番号"],
    "PickList.FilePrint.ItemName":  ["Item Name", "商品名"],
    "PickList.FilePrint.ItemName1":  ["Item Name1", "１行目"],
    "PickList.FilePrint.ItemName2":  ["Item Name2", "２行目"],
    "PickList.FilePrint.Location":  ["Location", "分類"],
//  "PickList.FilePrint.Location":  ["Location", "画面配置"],
    "PickList.FilePrint.Image":  ["Image", "画像"],
    "PickList.FilePrint.ImageName":  ["Image FileName", "画像ファイル名"],
    "PickList.FilePrint.BackGround":  ["BackGround", "背景色"],
    "PickList.ItemList.FileList": ["File List", "保存ファイル一覧"],
    "PickList.FileRemove.Guide": ["Selected file will be removed.<br> Are you sure.", "ファイルを削除します。<br>よろしいですか。"],
    "PickList.FileCreate.Title": ["Create New File", "新規作成"],
    "PickList.FileCreate.Guide": ["Please enter your new file name.", "新しいファイル名を入力してください。"],
    "PickList.FileCreate.InputEmptyName": ["Please fill in the file name.", "ファイル名を入力してください。"],
    "PickList.FileCreate.InValidName": ["Please fill in the file name a valid file name.", "ファイル名を正しく入力してください。"],
    "PickList.FileCreate.FileNameLengthOver": ["Please fill in the file name 50 characters.", "ファイル名を全角25文字以下にしてください。"],
    "PickList.FileCreate.NameLength": ["Up to 50 characters", "最大全角25文字"],
    "PickList.FileOpen.Guide": ["Please select a configuration file to open", "開くファイルを選択してください"],
    "PickList.FileSave.Title": ["Save File", "ファイルの保存"],
    "PickList.FileSave.Guide": ["Please input the file name for uploading.", "保存するファイル名を入力してください"],
    "PickList.FileSave.Overwrite": ["Overwrite existing file", "同名の既存ファイルがあれば上書きする"],
    "PickList.FileSave.AlreadyExists": ["File with the same name already exists!<br>Please change the file name, or turn on the overwrite option above.", "同じ名前のファイルがすでに存在します！<br>名前を変更するか、上の上書きオプションをオンにしてください。"],
    "PickList.FileSave.Guide.StatusSuccessful": ["File saving is completed!", "ファイルを保存しました！"],
    "PickList.FileSave.Guide.StatusFailed": ["File saving is failed!", "ファイルを保存失敗しました！"],
    "PickList.FileSave.FileId": ["Filename", "ファイル名"],
    "PickList.FileSave.NameLength": ["Up to 50 characters", "最大全角25文字"],
    "PickList.FileSave.InputEmptyName": ["Please fill in the file name.", "ファイル名を入力してください。"],
    "PickList.FileSave.InValidName": ["Please fill in the file name a valid file name.", "ファイル名を正しく入力してください。"],
    "PickList.FileSave.FileNameLengthOver": ["Please fill in the file name 50 characters.", "ファイル名を全角25文字以下に入力してください。"],
    "PickList.FileClose.Guide": ["The file is being closed.<br>Are you sure?", "ファイルを閉じます。<br><br>よろしいですか。"],
    "PickList.FileClose.AlreadyChanged": ["The file was changed. Do you want to save it before close?", "ファイルは変更されています。<br><br>保存せずに、ファイルを閉じますか。"],
    "PickList.EditItems.ComingSoon": ["Coming Soon", "準備中"],
    "PickList.EditItems.SelectImage": ["Select Image", "画像選択"],
    "PickList.EditItems.NoImage": ["No Image", "画像なし<br>(背景色)"],
    "PickList.EditItems.ItemId": ["Item Code", "商品番号"],
    "PickList.EditItems.ItemName": ["Item Name", "商品名"],
    "PickList.EditItems.Location": ["LocationName", "分類"],
    "PickList.EditItems.Create": ["Add Item", "新規商品追加"],
    "PickList.EditItems.ItemName.Line1": ["Name(1st line)", "商品名(1行目)"],
    "PickList.EditItems.ItemName.Line2": ["Name(2nd line)", "商品名(2行目)"],
    "PickList.EditItems.ImageFile": ["Item Image", "画像ファイル名"],
    "PickList.EditItems.ToRemove": ["The item is being deleted.<br>Are you sure?", "商品を削除します。<br>よろしいですか。"],
    "PickList.EditItems.ToNotRemove": ["The item is being used by Picture layout.<br>delete all", "この商品は、画面配置で使われています。<br>削除しますか"],
    "PickList.EditItems.ToRemoveLocation": ["Location:", "利用位置:"],
    "PickList.EditItems.Guide.Images": ["Please select the image", "画像を選択してください"],
    "PickList.EditItems.Guide.Background": ["Please select the buton color", "ボタンの色を選択してください"],
    "PickList.EditItems.MaxLength6": ["Max to 6 characters", "最大全角6文字"],
    "PickList.EditItems.MaxLength7": ["Max to 8 characters", "最大全角7文字"],
    "PickList.EditItems.MaxLength8": ["Max to 8 characters", "最大全角8文字"],
    "PickList.EditItems.MaxLength13": ["Max to 13 numbers", "半角数字最大13桁"],
    "PickList.EditCategories.Guide": ["Please select the category from the list", "編集したい分類を左のボタンから選択してください。"],
    "PickList.EditCategories.Category": ["Category #", "分類"],
    "PickList.EditCategories.Name.Line1": ["Name (1st Line)", "分類名（１行目）"],
    "PickList.EditCategories.Name.Line2": ["Name (2nd Line)", "分類名（２行目）"],
    "PickList.EditCategories.Effective": ["Effective", "表示する"],
    "PickList.EditCategories.MaxLength17": ["Max to 17 characters", "最大全角17文字"],
    "PickList.EditLayout.Guide": ["Please select an item", "商品を選択してください。"],
    "PickList.EditLayout.Unused": ["(Unused)", "(未使用)"],
    "PickList.EditLayout.ComingSoon": ["Coming Soon", "準備中"],
    "PickList.EditLayout.Blank": ["(Blank)", "(空白)"],
    "PickList.EditLayout.ClearTabItems": ["Clear items", "全クリア"],
    "PickList.EditLayout.ConfirmMessage": ["Change the unused buttons.<br><br>Are you sure you want?", "未使用ボタンに変更します。<br><br>よろしいですか。"],
    "PickList.EditLayout.ConfirmDelete": ["Remove from list", "商品一覧からも削除"],
    "PickList.EditLayout.ClearGuide": ["Delete all of the screen placement of the classification <br>that you are currently viewing.<br><br>Are you sure you want?", "現在表示している分類の画面配置を<br>すべて削除します。<br><br>よろしいですか？"],
//  "PickList.EditLayout.ConfirmRemove": ["Please select an item", "この商品は、商品一覧からも削除されます。<br><br>よろしいですか。"],

    "PickList.Failure.picklist.empty":["Please enter item code and name!","商品番号、または商品名が入力されていません。"],
    "PickList.Failure.picklist.blank":["Please apply item!","商品を適用してださい。"],
    "PickList.Failure.picklist.maxNumbers13":["Can not input more than 13 numbers!","商品番号には、最大13桁の数字(半角)を入力してください。"],
    "PickList.Failure.picklist.maxCharacters6":["Can not input more than 6 characters!","商品名には、全角6文字まで入力してください。"],
    "PickList.Failure.picklist.maxCharacters8":["Can not input more than 8 characters!","商品名には、全角8文字まで入力してください。"],
    "PickList.Failure.picklist.maxCharacters14":["Can not input more than 14 characters!","分類名には、全角7文字まで入力してください。"],
    "PickList.Failure.common.cleared":["",""],
//  "PickList.Failure.picklist.scheduled":["Can not delete ,File is used in deploy.", "削除できません。<br>適用が予定されているか、現在適用中です。"],
    "PickList.Failure.picklist.scheduled":["It is currently being applied. <br>If you want to delete, please delivery by setting the expiration date to a past date..",
                                                                                 "現在適用中です。<br>削除する場合は、有効期限を過去の日付に設定して配信してください。"],
    "PickList.Popup.OK": ["OK", "確認"],
    
    "Advertise.Button.Yes": ["Yes", "はい"],
    "Advertise.Button.No": ["No", "いいえ"],
    "Advertise.Button.Okay": ["OK", "確認"],
    "Advertise.Button.Open": ["Open", "開く"],
    "Advertise.Button.Create": ["Create", "作成"],
    "Advertise.Button.Save": ["Save", "保存"],
    "Advertise.Button.Cancel": ["Cancel", "中止"],
    "Advertise.Button.Import": ["ImportImage", "画像取込"],
    "Advertise.Button.Delete": ["Delete", "削除"],
    "Advertise.Back": ["Back", "戻る"],
    "Advertise.Submit": ["Submit", "確定"],
    "Advertise.Apply": ["Apply", "適用"],
    "Advertise.Void": ["Void", "取消<br>(元に戻す)"],
    "Advertise.Delete": ["Delete", "削除"],
    "Advertise.Menu.Exit": ["Exit", "終了"],
    "Advertise.Menu.FileCreate": ["Create", "新規作成"],
    "Advertise.Menu.FileOpen": ["Open", "開く"],
    "Advertise.Menu.FileRemove": ["Remove", "削除"],
    "Advertise.Menu.FileSave": ["Save", "保存"],
    "Advertise.Menu.FileClose": ["Cancel", "中止"],
    "Advertise.Menu.FileImport": ["Import", "読み込み"],
    "Advertise.Menu.FileName": ["File:", "ファイル名:"],
    "Advertise.Menu.EditItems": ["Items", "商品一覧"],
    "Advertise.Menu.EditCategories": ["Categories", "分類"],
    "Advertise.Menu.EditLayout": ["Layout", "画面配置"],
    "Advertise.Menu.FilePrint": ["Print", "印刷"],
    "Advertise.Menu.ClearTabItems": ["Clear items", "全クリア"],
    "Advertise.FilePrint.FileName":  ["FileName", "ファイル名："],
    "Advertise.FilePrint.ItemId":  ["Item Code", "商品番号"],
    "Advertise.FilePrint.ItemName":  ["Item Name", "商品名"],
    "Advertise.FilePrint.ItemName1":  ["Item Name1", "１行目"],
    "Advertise.FilePrint.ItemName2":  ["Item Name2", "２行目"],
    "Advertise.FilePrint.Location":  ["Location", "分類"],
//  "Advertise.FilePrint.Location":  ["Location", "画面配置"],
    "Advertise.FilePrint.Image":  ["Image", "画像"],
    "Advertise.FilePrint.ImageName":  ["Image FileName", "画像ファイル名"],
    "Advertise.FilePrint.BackGround":  ["BackGround", "背景色"],
    "Advertise.ItemList.FileList": ["File List", "保存ファイル一覧"],
    "Advertise.FileRemove.Guide": ["Selected file will be removed.<br> Are you sure.", "ファイルを削除します。<br>よろしいですか。"],
    "Advertise.FileCreate.Title": ["Create New File", "新規作成"],
    "Advertise.FileCreate.Guide": ["Please enter your new file name.", "新しいファイル名を入力してください。"],
    "Advertise.FileCreate.InputEmptyName": ["Please fill in the file name.", "ファイル名を入力してください。"],
    "Advertise.FileCreate.InValidName": ["Please fill in the file name a valid file name.", "ファイル名を正しく入力してください。"],
    "Advertise.FileCreate.FileNameLengthOver": ["Please fill in the file name 50 characters.", "ファイル名を全角25文字以下にしてください。"],
    "Advertise.FileCreate.NameLength": ["Up to 50 characters", "最大全角25文字"],
    "Advertise.FileOpen.Guide": ["Please select a configuration file to open", "開くファイルを選択してください"],
    "Advertise.FileSave.Title": ["Save File", "ファイルの保存"],
    "Advertise.FileSave.Guide": ["Please input the file name for uploading.", "保存するファイル名を入力してください"],
    "Advertise.FileSave.Overwrite": ["Overwrite existing file", "同名の既存ファイルがあれば上書きする"],
    "Advertise.FileSave.AlreadyExists": ["File with the same name already exists!<br>Please change the file name, or turn on the overwrite option above.", "同じ名前のファイルがすでに存在します！<br>名前を変更するか、上の上書きオプションをオンにしてください。"],
    "Advertise.FileSave.Guide.StatusSuccessful": ["File saving is completed!", "ファイルを保存しました！"],
    "Advertise.FileSave.Guide.StatusFailed": ["File saving is failed!", "ファイルを保存失敗しました！"],
    "Advertise.FileSave.FileId": ["Filename", "ファイル名"],
    "Advertise.FileSave.NameLength": ["Up to 50 characters", "最大全角25文字"],
    "Advertise.FileSave.InputEmptyName": ["Please fill in the file name.", "ファイル名を入力してください。"],
    "Advertise.FileSave.InValidName": ["Please fill in the file name a valid file name.", "ファイル名を正しく入力してください。"],
    "Advertise.FileSave.FileNameLengthOver": ["Please fill in the file name 50 characters.", "ファイル名を全角25文字以下に入力してください。"],
    "Advertise.FileClose.Guide": ["The file is being closed.<br>Are you sure?", "ファイルを閉じます。<br><br>よろしいですか。"],
    "Advertise.FileClose.AlreadyChanged": ["The file was changed. Do you want to save it before close?", "ファイルは変更されています。<br><br>保存せずに、ファイルを閉じますか。"],
    "Advertise.EditItems.ComingSoon": ["Coming Soon", "準備中"],
    "Advertise.EditItems.SelectImage": ["Select Image", "画像選択"],
    "Advertise.EditItems.NoImage": ["No Image", "画像なし<br>(背景色)"],
    "Advertise.EditItems.StartOfSay": ["Start Of Day", "開始日付"],
    "Advertise.EditItems.EndOfSay": ["End Of Say", "終了日付"],
    "Advertise.EditItems.CompanyName": ["Company Name", "会社名"],
    "Advertise.EditItems.ADName": ["AD Name", "広告名"],
    "Advertise.EditItems.Description": ["Description", "説明"],
    "Advertise.EditItems.ItemName": ["Item Name", "商品名"],
    "Advertise.EditItems.Location": ["LocationName", "分類"],
    "Advertise.EditItems.Create": ["Add Item", "新規商品追加"],
    "Advertise.EditItems.ItemName.Line1": ["Name(1st line)", "商品名(1行目)"],
    "Advertise.EditItems.ItemName.Line2": ["Name(2nd line)", "商品名(2行目)"],
    "Advertise.EditItems.ImageFile": ["Item Image", "画像ファイル名"],
    "Advertise.EditItems.ToRemove": ["The AD image is being deleted.<br>Are you sure?", "広告イメージを削除します。<br>よろしいですか。"],
    "Advertise.EditItems.ToNotRemove": ["The item is being used by Picture layout.<br>delete all", "この商品は、画面配置で使われています。<br>削除しますか"],
    "Advertise.EditItems.ToRemoveLocation": ["Location:", "利用位置:"],
    "Advertise.EditItems.Guide.Images": ["Please select the image", "画像を選択してください"],
    "Advertise.EditItems.Guide.Background": ["Please select the buton color", "ボタンの色を選択してください"],
    "Advertise.EditItems.MaxLength6": ["Max to 6 characters", "最大全角6文字"],
    "Advertise.EditItems.MaxLength7": ["Max to 8 characters", "最大全角7文字"],
    "Advertise.EditItems.MaxLength8": ["Max to 8 characters", "最大全角8文字"],
    "Advertise.EditItems.MaxLength16": ["Max to 8 characters", "最大全角16文字"],
    "Advertise.EditItems.MaxLength13": ["Max to 13 numbers", "半角数字最大13桁"],
    "Advertise.EditCategories.Guide": ["Please select the category from the list", "編集したい分類を左のボタンから選択してください。"],
    "Advertise.EditCategories.Category": ["Category #", "分類"],
    "Advertise.EditCategories.Name.Line1": ["Name (1st Line)", "分類名（１行目）"],
    "Advertise.EditCategories.Name.Line2": ["Name (2nd Line)", "分類名（２行目）"],
    "Advertise.EditCategories.Effective": ["Effective", "表示する"],
    "Advertise.EditCategories.MaxLength17": ["Max to 17 characters", "最大全角17文字"],
    "Advertise.EditLayout.Guide": ["Please select an item", "商品を選択してください。"],
    "Advertise.EditLayout.Unused": ["(Unused)", "(未使用)"],
    "Advertise.EditLayout.ComingSoon": ["Coming Soon", "準備中"],
    "Advertise.EditLayout.Blank": ["(Blank)", "(空白)"],
    "Advertise.EditLayout.ClearTabItems": ["Clear items", "全クリア"],
    "Advertise.EditLayout.AddTabItems": ["Add items", "追加"],
    "Advertise.EditLayout.smallPicture": ["Small picture", "600 X 640 イメージ"],
    "Advertise.EditLayout.bigPicture": ["Big picture", "1020 X 640 イメージ"],
    "Advertise.EditLayout.fileName": ["File Name", "ファイル名(最大全角8文字)"],
    "Advertise.EditLayout.Interval": ["Time Interval", "スライド間隔"],
    "Advertise.EditLayout.Unit": ["Second", "秒"],
    "Advertise.EditLayout.ConfirmMessage": ["Change the unused buttons.<br><br>Are you sure you want?", "未使用ボタンに変更します。<br><br>よろしいですか。"],
    "Advertise.EditLayout.ConfirmDelete": ["Remove from list", "商品一覧からも削除"],
    "Advertise.EditLayout.ClearGuide": ["Delete all of the screen placement of the classification <br>that you are currently viewing.<br><br>Are you sure you want?", "現在表示している分類の画面配置を<br>すべて削除します。<br><br>よろしいですか？"],
//  "Advertise.EditLayout.ConfirmRemove": ["Please select an item", "この商品は、商品一覧からも削除されます。<br><br>よろしいですか。"],

    "Advertise.Failure.picklist.empty":["Please enter item code and name!","商品番号、または商品名が入力されていません。"],
    "Advertise.Failure.picklist.blank":["Please apply item!","商品を適用してださい。"],
    "Advertise.Failure.picklist.maxNumbers13":["Can not input more than 13 numbers!","商品番号には、最大13桁の数字(半角)を入力してください。"],
    "Advertise.Failure.picklist.maxCharacters6":["Can not input more than 6 characters!","商品名には、全角6文字まで入力してください。"],
    "Advertise.Failure.picklist.maxCharacters8":["Can not input more than 8 characters!","商品名には、全角8文字まで入力してください。"],
    "Advertise.Failure.picklist.maxCharacters14":["Can not input more than 14 characters!","分類名には、全角7文字まで入力してください。"],
    "Advertise.Failure.common.cleared":["",""],
//  "Advertise.Failure.picklist.scheduled":["Can not delete ,File is used in deploy.", "削除できません。<br>適用が予定されているか、現在適用中です。"],
    "Advertise.Failure.picklist.scheduled":["It is currently being applied. <br>If you want to delete, please delivery by setting the expiration date to a past date..",
                                                                                 "現在適用中です。<br>削除する場合は、有効期限を過去の日付に設定して配信してください。"],
    "Advertise.Popup.OK": ["OK", "確認"],

    "Settings.Button.Change": ["Change","変更"],
    "Settings.TableOfContents.Title": ["Settings", "各種設定"],
    "Settings.TableOfContents.Device": ["Device Settings", "端末設定"],
    "Settings.TableOfContents.Printer": ["Printer Settings", "プリンター設定"],
    "Settings.TableOfContents.Transfer": ["Transfering Data", "他の端末との連動"],
    "Settings.TableOfContents.Personal": ["Personal Settings", "個人設定"],
    "Settings.TableOfContents.Software": ["Software", "ソフトウェア"],
    "Settings.Device.Title": ["Device Settings", "端末設定"],
    "Settings.Device.Back": ["Back", "戻る"],
    "Settings.Device.OtherCompany": ["Other Company (10 Key)", "その他の企業（番号手入力)"],
    "Settings.Device.CompanyID": ["Company ID", "企業番号"],
    "Settings.Device.CompanyID.Title": ["Company ID", "企業番号"],
    "Settings.Device.StoreID": ["Store ID", "店舗番号"],
    "Settings.Device.StoreID.Title": ["Store ID", "店舗番号"],
    "Settings.Device.WorkstationID": ["Terminal ID", "レジ番号・端末番号"],
    "Settings.Device.WorkstationID.Title": ["Terminal ID", "レジ番号・端末番号"],
    "Settings.Device.Language": ["Language", "言語(Language)"],
    "Settings.Device.Language.Title": ["Language", "言語"],
    "Settings.Device.Language.en": ["English", "英語(English)"],
    "Settings.Device.Language.ja": ["Japanese", "日本語(Japanese)"],
//  "Settings.Device.Restart": ["Restart", "再起動"],
//  "Settings.Device.Restart": ["Set", "設定"],
    "Settings.Device.Restart": ["Restart", "設定終了"],
    "Settings.Device.RestartOpen": ["ReOpen", "開始"],
    "Settings.Device.Cursor": ["Show mouse pointer", "マウスポインターを表示"],
    "Settings.Device.Volume": ["Volume", "音量"],
    "Settings.Device.Deregister": ["Deregister", "登録解除"],
    "Settings.Software.Core": ["internal Log", "内部ログ"],
    "Settings.Software.Restore": ["Restore", "再読込み"],
    "Settings.Software.Close": ["Exit", "終了"],
    "Settings.Printer.Title": ["Please select printer", "接続するプリンターを選択してください。"],
    "Settings.Transfer.Title": ["Please select target device", "接続する端末を選択してください。"],
    "Settings.Personal.Title": ["Change Password", "パスワード変更"],
    "Settings.Personal.OldPassword": ["Old Password", "旧パスワード"],
    "Settings.Personal.NewPassword": ["New Password", "新パスワード"],
    "Settings.Personal.ReEnter": ["ReEnter", "再入力"],
    "Settings.Personal.Training": ["Training mode", "トレーニングモード"],

    "SidePanel.Home":   ["Home", "ホーム"],
    "SidePanel.Deploy": ["Schedule","配信予定"],
    "SidePanel.Settings": ["Settings","各種設定"],
    "SidePanel.Lock": ["Lock", "一時休止"],
    "SidePanel.LogOut": ["Sign Out", "休止"],

    "Popup.Wait": ["Processing...", "集配信中"],

    "none":     ["",""]
};
