/*
 * Copyright (c) 2011 NCR/JAPAN Corporation SW-R&D
 *
 * ReportParam
 *
 * Model for the details that identifies the type of a report
 * to be generated by the ReportResource
 *
 * Meneses, Chris Niven
 */
package ncr.res.mobilepos.report.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Fields Class is a Model representation of the information which identifies
 * the report type.
 */
@XmlAccessorType(XmlAccessType.NONE)
@XmlRootElement(name = "Fields")
public class SalesReportFields {

    /** Identifies the Sales report type. */
    @XmlElement(name = "SalesReportType")
    private String salesReportType;

    /** Enumerates the details of a Detail type report. */
    @XmlElement(name = "Details")
    private Details details;

    /**
     * Retrieves the Sales Report Type.
     *
     * @return Sales Report Type
     */
    public final String getSalesReportType() {
        return salesReportType;
    }

    /**
     * Sets the Sales Report Type.
     *
     * @param salesReportTypeToSet
     *            the new sales report type
     */
    public final void setSalesReportType(final String salesReportTypeToSet) {
        this.salesReportType = salesReportTypeToSet;
    }

    /**
     * Retrieves the Details.
     *
     * @return Details
     */
    public final Details getDetails() {
        return details;
    }

    /**
     * Sets the Details.
     *
     * @param detailsToSet
     *            the new details
     */
    public final void setDetails(final Details detailsToSet) {
        this.details = detailsToSet;
    }
}
